### ISSUE TITLE
Find HOES returns my own ip

### ISSUE THREAD

**Issue by bearsh** [bart-kneepkens/OpenHeosControl#2]
If I press the 'Find HOES' button, my own address is filled in instead of the address of one of my speakers.
I use the jar bundle, version 0.2

**Comment by bart-kneepkens** [comment]
Excuse me for the delay in getting back to your issue.
I am unable to reproduce this issue, and I have no idea why the M-Search seems to fail, but I can tell you that the next version (0.3) will contain an option to manually enter an IP address and connect to it.

For now, I suggest that you download the source code from 0.2, and remove `Main.java`'s line 105. (`ipTextField.setEditable(false);`)

Then, after you compile and run the app, you should be able to enter your HEOS IP address yourself and connect to it.

If you run into any more problems, please let me know.

**Comment by bearsh** [comment]
thanks. I'm gonna try it as soon as I have the time (which can take a while...)
let's close it for now...

**Comment by lsh-0** [comment]
"find HOES" - it's so immature, but I love it. It also adds a twist to "OpenHoesControl"... 

... all that nonsense aside and completely off topic, I wanted to thank you @bart-kneepkens for your work on this project. The official android app now requires mandatory location access, which I refuse, and thus the remote control has been rendered useless. I hope to contribute something to your project in the future.

**Comment by bart-kneepkens** [comment]
Hey Ish-0. Thanks for your comments. Indeed, mandatory location access for the HEOS controller app is unacceptable. 

If you’re looking to find hoes i’d recommend going to your local utilities store and finding one there. It’s an absolute essential for gardening.

In all seriousness, I’d like to continue on this project but I’m currently not in the possession of a HEOS device. I’m looking for one, though.
